# TASK 3 · Cleaning Data

## 📌 About the Project

**This project demonstrates a complete **Data Cleaning and Preprocessing workflow using Python, Pandas, NumPy, and Jupyter Notebook**. The raw dataset was analyzed for missing values, duplicate records, inconsistent formatting, incorrect data types, invalid values, and potential outliers. Appropriate cleaning techniques such as median imputation, categorical standardisation, duplicate handling, data type correction, and IQR-based outlier detection were applied. A before-vs-after data quality comparison was also performed, and the final cleaned dataset was exported as a new CSV file ready for further analysis.**

In [2]:
# Import pandas for data manipulation and analysis
import pandas as pd

# Import numpy for numerical operations
import numpy as np

# Load the CSV dataset

In [4]:
# Load the CSV dataset
df = pd.read_csv("tested.csv")

# Display the first 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

# Display number of rows and columns

In [7]:
# Display number of rows and columns
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 418
Number of columns: 12

# Display complete information about the dataset

In [6]:
# Display complete information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

# Display all column names

In [8]:
# Display all column names
print("Columns in dataset:")
print(df.columns.tolist())

Columns in dataset:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

# Generate descriptive statistics for numerical columns

In [9]:
# Generate descriptive statistics for numerical columns
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

# Count missing values in every column

In [10]:
# Count missing values in every column
null_report = pd.DataFrame({
    "Column": df.columns,
    "Null_Count": df.isnull().sum().values,
    "Null_Percentage": (
        df.isnull().sum().values / len(df) * 100
    ).round(2)
})

null_report

         Column  Null_Count  Null_Percentage
0   PassengerId           0             0.00
1      Survived           0             0.00
2        Pclass           0             0.00
3          Name           0             0.00
4           Sex           0             0.00
5           Age          86            20.57
6         SibSp           0             0.00
7         Parch           0             0.00
8        Ticket           0             0.00
9          Fare           1             0.24
10        Cabin         327            78.23
11     Embarked           0             0.00

# Calculate total number of missing cells

In [11]:
# Calculate total number of missing cells
total_missing = df.isnull().sum().sum()

print("Total missing values:", total_missing)

Total missing values: 414

# Count completely duplicated rows

In [12]:
# Count completely duplicated rows
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [13]:
# Display duplicate rows if any exist
df[df.duplicated()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

# Display data types of all columns

In [14]:
# Display data types of all columns
dtype_report = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values
})

dtype_report

         Column Data_Type
0   PassengerId     int64
1      Survived     int64
2        Pclass     int64
3          Name    object
4           Sex    object
5           Age   float64
6         SibSp     int64
7         Parch     int64
8        Ticket    object
9          Fare   float64
10        Cabin    object
11     Embarked    object

# Define expected data types

In [15]:
# Define expected data types
expected_dtypes = {
    "PassengerId": "string",
    "Survived": "integer",
    "Pclass": "integer",
    "Name": "string",
    "Sex": "string",
    "Age": "float",
    "SibSp": "integer",
    "Parch": "integer",
    "Ticket": "string",
    "Fare": "float",
    "Cabin": "string",
    "Embarked": "string"
}

print("Expected data types:")
for column, dtype in expected_dtypes.items():
    print(column, "->", dtype)

Expected data types:
PassengerId -> string
Survived -> integer
Pclass -> integer
Name -> string
Sex -> string
Age -> float
SibSp -> integer
Parch -> integer
Ticket -> string
Fare -> float
Cabin -> string
Embarked -> string

In [16]:
# Display complete information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [17]:
# Check unique values for categorical columns

print("Sex values:")
print(df["Sex"].unique())

print("\nEmbarked values:")
print(df["Embarked"].unique())

print("\nPclass values:")
print(df["Pclass"].unique())

print("\nSurvived values:")
print(df["Survived"].unique())

Sex values:
['male' 'female']

Embarked values:
['Q' 'S' 'C']

Pclass values:
[3 2 1]

Survived values:
[0 1]

In [18]:
# Get all text/object columns
text_columns = df.select_dtypes(include=["object"]).columns

print("Text columns:")
print(text_columns.tolist())

Text columns:
['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [20]:
# Remove leading and trailing spaces from text columns
for column in text_columns:
    df[column] = df[column].str.strip()

In [21]:
# Standardise Sex/Gender values
df["Sex"] = (
    df["Sex"]
    .astype("string")
    .str.strip()
    .str.lower()
    .replace({
        "m": "Male",
        "male": "Male",
        "f": "Female",
        "female": "Female"
    })
)

# Check the final values
print(df["Sex"].unique())

<StringArray>
['Male', 'Female']
Length: 2, dtype: string

# Remove spaces and convert Embarked values to uppercase

In [22]:
# Remove spaces and convert Embarked values to uppercase
df["Embarked"] = (
    df["Embarked"]
    .astype("string")
    .str.strip()
    .str.upper()
)

# Check unique values
print(df["Embarked"].unique())

<StringArray>
['Q', 'S', 'C']
Length: 3, dtype: string

In [23]:
# Remove unnecessary spaces from Name and Ticket
df["Name"] = df["Name"].astype("string").str.strip()
df["Ticket"] = df["Ticket"].astype("string").str.strip()

# Display the standardised categorical values

In [25]:
# Display the standardised categorical values
print("Sex values:")
print(df["Sex"].unique())

print("\nEmbarked values:")
print(df["Embarked"].unique())

# Check data types
print("\nData types:")
print(df[["Sex", "Embarked", "Name", "Ticket"]].dtypes)

Sex values:
<StringArray>
['Male', 'Female']
Length: 2, dtype: string

Embarked values:
<StringArray>
['Q', 'S', 'C']
Length: 3, dtype: string

Data types:
Sex         string[python]
Embarked    string[python]
Name        string[python]
Ticket      string[python]
dtype: object

# Check unique values for categorical columns

In [26]:
# Check unique values for categorical columns

print("Sex values:")
print(df["Sex"].unique())

print("\nEmbarked values:")
print(df["Embarked"].unique())

print("\nPclass values:")
print(df["Pclass"].unique())

print("\nSurvived values:")
print(df["Survived"].unique())

Sex values:
<StringArray>
['Male', 'Female']
Length: 2, dtype: string

Embarked values:
<StringArray>
['Q', 'S', 'C']
Length: 3, dtype: string

Pclass values:
[3 2 1]

Survived values:
[0 1]

# Select numerical columns

In [27]:
# Select numerical columns
numeric_columns = df.select_dtypes(include=np.number).columns

# Create range report
range_report = pd.DataFrame({
    "Column": numeric_columns,
    "Minimum": [df[col].min() for col in numeric_columns],
    "Maximum": [df[col].max() for col in numeric_columns],
    "Mean": [df[col].mean() for col in numeric_columns]
})

range_report

        Column  Minimum    Maximum         Mean
0  PassengerId   892.00  1309.0000  1100.500000
1     Survived     0.00     1.0000     0.363636
2       Pclass     1.00     3.0000     2.265550
3          Age     0.17    76.0000    30.272590
4        SibSp     0.00     8.0000     0.447368
5        Parch     0.00     9.0000     0.392344
6         Fare     0.00   512.3292    35.627188

In [28]:
# Check whether Survived contains only 0 and 1
invalid_survived = df[~df["Survived"].isin([0, 1])]

print("Invalid Survived values:", len(invalid_survived))

Invalid Survived values: 0

In [29]:
# Check whether passenger class is only 1, 2, or 3
invalid_pclass = df[~df["Pclass"].isin([1, 2, 3])]

print("Invalid Pclass values:", len(invalid_pclass))

Invalid Pclass values: 0

In [30]:
# Check for impossible negative ages
invalid_age = df[df["Age"] < 0]

print("Invalid negative ages:", len(invalid_age))

Invalid negative ages: 0

In [31]:
# Check for negative fares
invalid_fare = df[df["Fare"] < 0]

print("Invalid negative fares:", len(invalid_fare))

Invalid negative fares: 0

## 13. Missing Data Handling Strategy
This is an important Markdown cell for your notebook.
Missing Data Strategy
Age
The Age column contains 86 missing values. Age is a numerical variable, and passenger ages are not normally distributed perfectly. Therefore, median imputation is preferred because the median is less affected by extreme ages than the mean.
Fare
Only one value is missing in Fare. Since Fare is numerical, the median Fare is used. This avoids deleting an otherwise useful passenger record.
Cabin
The Cabin column has a large number of missing values. Deleting 327 rows would remove most of the dataset. Therefore, missing cabin information is replaced with "Unknown" rather than deleting rows.
Other columns
Other columns contain no missing values, so no imputation is required.

In [32]:
# Create a copy of the original dataset
cleaned_df = df.copy()

# Check that the copy was created
cleaned_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",Male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",Female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",Male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",Male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",Female,22.0,1,1,3101298,12.2875,NaN,S

In [33]:
# Calculate median age
age_median = cleaned_df["Age"].median()

print("Median Age:", age_median)

Median Age: 27.0

In [34]:
# Fill missing Age values with the median
cleaned_df["Age"] = cleaned_df["Age"].fillna(age_median)

# Check missing values again
print("Missing Age after imputation:", cleaned_df["Age"].isnull().sum())

Missing Age after imputation: 0

In [35]:
# Calculate median Fare
fare_median = cleaned_df["Fare"].median()

print("Median Fare:", fare_median)

Median Fare: 14.4542

In [36]:
# Fill missing Fare values with median Fare
cleaned_df["Fare"] = cleaned_df["Fare"].fillna(fare_median)

# Check missing Fare values
print("Missing Fare after imputation:", cleaned_df["Fare"].isnull().sum())

Missing Fare after imputation: 0

In [37]:
# Replace missing Cabin values with "Unknown"
cleaned_df["Cabin"] = cleaned_df["Cabin"].fillna("Unknown")

# Check missing Cabin values
print("Missing Cabin after cleaning:", cleaned_df["Cabin"].isnull().sum())

Missing Cabin after cleaning: 0

# Display missing values after imputation

In [38]:
# Display missing values after imputation
missing_after_imputation = cleaned_df.isnull().sum()

missing_after_imputation

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

# Calculate total remaining missing values

In [39]:
# Calculate total remaining missing values
print(
    "Total missing values after imputation:",
    cleaned_df.isnull().sum().sum()
)

Total missing values after imputation: 0

## Duplicate Removal
Even though the dataset currently contains zero duplicates, the cleaning workflow should still explicitly perform duplicate removal.

In [40]:
# Count duplicate rows before removal
duplicates_before = cleaned_df.duplicated().sum()

print("Duplicate rows before removal:", duplicates_before)

Duplicate rows before removal: 0

In [41]:
# Remove duplicate rows
cleaned_df = cleaned_df.drop_duplicates()

# Reset index after removing duplicates
cleaned_df = cleaned_df.reset_index(drop=True)

# Count duplicates after removal
duplicates_after = cleaned_df.duplicated().sum()

print("Duplicate rows after removal:", duplicates_after)

Duplicate rows after removal: 0

In [42]:
# Identify text columns
text_columns = cleaned_df.select_dtypes(include="object").columns

# Remove leading/trailing spaces
for column in text_columns:
    cleaned_df[column] = cleaned_df[column].str.strip()

In [43]:
# Standardise gender values
cleaned_df["Sex"] = cleaned_df["Sex"].str.strip().str.lower()

# Convert values into consistent title case
cleaned_df["Sex"] = cleaned_df["Sex"].str.title()

# Check values
cleaned_df["Sex"].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: string

In [44]:
# Remove spaces and convert Embarked values to uppercase
cleaned_df["Embarked"] = (
    cleaned_df["Embarked"]
    .str.strip()
    .str.upper()
)

# Check unique values
cleaned_df["Embarked"].unique()

<StringArray>
['Q', 'S', 'C']
Length: 3, dtype: string

In [45]:
# Convert PassengerId to string
cleaned_df["PassengerId"] = cleaned_df["PassengerId"].astype("string")

In [46]:
# Convert Ticket to string
cleaned_df["Ticket"] = cleaned_df["Ticket"].astype("string")

In [47]:
# Convert text columns to pandas StringDtype
cleaned_df["Name"] = cleaned_df["Name"].astype("string")
cleaned_df["Sex"] = cleaned_df["Sex"].astype("string")
cleaned_df["Cabin"] = cleaned_df["Cabin"].astype("string")
cleaned_df["Embarked"] = cleaned_df["Embarked"].astype("string")

In [48]:
# Convert integer columns to integer dtype
cleaned_df["Survived"] = cleaned_df["Survived"].astype("int64")
cleaned_df["Pclass"] = cleaned_df["Pclass"].astype("int64")
cleaned_df["SibSp"] = cleaned_df["SibSp"].astype("int64")
cleaned_df["Parch"] = cleaned_df["Parch"].astype("int64")

In [49]:
# Convert Age to float
cleaned_df["Age"] = cleaned_df["Age"].astype("float64")

# Convert Fare to float
cleaned_df["Fare"] = cleaned_df["Fare"].astype("float64")

# Display final data types

In [50]:
# Display final data types
cleaned_df.dtypes

PassengerId    string[python]
Survived                int64
Pclass                  int64
Name           string[python]
Sex            string[python]
Age                   float64
SibSp                   int64
Parch                   int64
Ticket         string[python]
Fare                  float64
Cabin          string[python]
Embarked       string[python]
dtype: object

## Outlier Detection Using IQR
The Interquartile Range (IQR) method is used to identify potential outliers.

In [51]:
# Select numerical columns
numeric_columns = cleaned_df.select_dtypes(include=np.number).columns

# Create an empty dictionary for outlier information
outlier_report = {}

# Loop through numerical columns
for column in numeric_columns:
    
    # Calculate Q1 and Q3
    Q1 = cleaned_df[column].quantile(0.25)
    Q3 = cleaned_df[column].quantile(0.75)
    
    # Calculate IQR
    IQR = Q3 - Q1
    
    # Calculate lower and upper limits
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR
    
    # Identify outliers
    outliers = cleaned_df[
        (cleaned_df[column] < lower_limit) |
        (cleaned_df[column] > upper_limit)
    ]
    
    # Store results
    outlier_report[column] = {
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Limit": lower_limit,
        "Upper Limit": upper_limit,
        "Outlier Count": len(outliers)
    }

# Convert dictionary into DataFrame
outlier_report_df = pd.DataFrame(outlier_report).T

outlier_report_df

,Q1,Q3,IQR,Lower Limit,Upper Limit,Outlier Count
Survived,0.0000,1.000000,1.000000,-1.500000,2.500000,0.0
Pclass,1.0000,3.000000,2.000000,-2.000000,6.000000,0.0
Age,23.0000,35.750000,12.750000,3.875000,54.875000,36.0
SibSp,0.0000,1.000000,1.000000,-1.500000,2.500000,11.0
Parch,0.0000,0.000000,0.000000,0.000000,0.000000,94.0
Fare,7.8958,31.471875,23.576075,-27.468312,66.835988,55.0

# Display number of potential outliers in each numerical column

In [52]:
# Display number of potential outliers in each numerical column

for column in numeric_columns:
    
    Q1 = cleaned_df[column].quantile(0.25)
    Q3 = cleaned_df[column].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR
    
    count = (
        (cleaned_df[column] < lower_limit) |
        (cleaned_df[column] > upper_limit)
    ).sum()
    
    print(column, ":", count, "potential outliers")

Survived : 0 potential outliers
Pclass : 0 potential outliers
Age : 36 potential outliers
SibSp : 11 potential outliers
Parch : 94 potential outliers
Fare : 55 potential outliers

In [53]:
# Display final number of rows and columns
print("Final rows:", cleaned_df.shape[0])
print("Final columns:", cleaned_df.shape[1])

Final rows: 418
Final columns: 12

In [54]:
# Calculate total null cells before cleaning
null_before = df.isnull().sum().sum()

# Calculate total null cells after cleaning
null_after = cleaned_df.isnull().sum().sum()

print("Null values before:", null_before)
print("Null values after:", null_after)

Null values before: 414
Null values after: 0

In [55]:
# Duplicate count before cleaning
duplicate_before = df.duplicated().sum()

# Duplicate count after cleaning
duplicate_after = cleaned_df.duplicated().sum()

print("Duplicates before:", duplicate_before)
print("Duplicates after:", duplicate_after)

Duplicates before: 0
Duplicates after: 0

# Function to check whether a column has the expected dtype

In [57]:
# Function to check whether a column has the expected dtype

def check_dtype_accuracy(dataframe):
    
    results = {}
    
    results["PassengerId"] = str(dataframe["PassengerId"].dtype) == "string"
    results["Survived"] = str(dataframe["Survived"].dtype) == "int64"
    results["Pclass"] = str(dataframe["Pclass"].dtype) == "int64"
    results["Name"] = str(dataframe["Name"].dtype) == "string"
    results["Sex"] = str(dataframe["Sex"].dtype) == "string"
    results["Age"] = str(dataframe["Age"].dtype) == "float64"
    results["SibSp"] = str(dataframe["SibSp"].dtype) == "int64"
    results["Parch"] = str(dataframe["Parch"].dtype) == "int64"
    results["Ticket"] = str(dataframe["Ticket"].dtype) == "string"
    results["Fare"] = str(dataframe["Fare"].dtype) == "float64"
    results["Cabin"] = str(dataframe["Cabin"].dtype) == "string"
    results["Embarked"] = str(dataframe["Embarked"].dtype) == "string"
    
    return results

# Check dtype accuracy before cleaning

In [58]:
# Check dtype accuracy before cleaning
before_dtype_results = check_dtype_accuracy(
    df.astype({
        "PassengerId": "string",
        "Name": "string",
        "Sex": "string",
        "Ticket": "string",
        "Cabin": "string",
        "Embarked": "string"
    })
)

# Check dtype accuracy after cleaning
after_dtype_results = check_dtype_accuracy(cleaned_df)

print("Dtype accuracy after cleaning:")
print(all(after_dtype_results.values()))

Dtype accuracy after cleaning:
True

# Create final comparison table

In [59]:
# Create final comparison table

before_dtype_accuracy = "Needs correction"
after_dtype_accuracy = "Correct"

before_after_summary = pd.DataFrame({
    "Metric": [
        "Row Count",
        "Column Count",
        "Total Null Values",
        "Duplicate Rows",
        "Dtype Accuracy"
    ],
    
    "Before Cleaning": [
        len(df),
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        before_dtype_accuracy
    ],
    
    "After Cleaning": [
        len(cleaned_df),
        cleaned_df.shape[1],
        cleaned_df.isnull().sum().sum(),
        cleaned_df.duplicated().sum(),
        after_dtype_accuracy
    ]
})

before_after_summary

              Metric   Before Cleaning After Cleaning
0          Row Count               418            418
1       Column Count                12             12
2  Total Null Values               414              0
3     Duplicate Rows                 0              0
4     Dtype Accuracy  Needs correction        Correct

# Create column-level comparison

In [60]:
# Create column-level comparison

column_comparison = pd.DataFrame({
    "Column": df.columns,
    "Null Before": df.isnull().sum().values,
    "Null After": cleaned_df.isnull().sum().values,
    "Dtype Before": df.dtypes.astype(str).values,
    "Dtype After": cleaned_df.dtypes.astype(str).values
})

column_comparison

         Column  Null Before  Null After Dtype Before Dtype After
0   PassengerId            0           0        int64      string
1      Survived            0           0        int64       int64
2        Pclass            0           0        int64       int64
3          Name            0           0       string      string
4           Sex            0           0       string      string
5           Age           86           0      float64     float64
6         SibSp            0           0        int64       int64
7         Parch            0           0        int64       int64
8        Ticket            0           0       string      string
9          Fare            1           0      float64     float64
10        Cabin          327           0       object      string
11     Embarked            0           0       string      string

# Check for remaining missing values

In [61]:
# Check for remaining missing values
print("Total missing values:", cleaned_df.isnull().sum().sum())

# Check for remaining duplicates
print("Total duplicate rows:", cleaned_df.duplicated().sum())

# Check dataset shape
print("Final shape:", cleaned_df.shape)

# Check data types
print("\nFinal data types:")
print(cleaned_df.dtypes)

Total missing values: 0
Total duplicate rows: 0
Final shape: (418, 12)

Final data types:
PassengerId    string[python]
Survived                int64
Pclass                  int64
Name           string[python]
Sex            string[python]
Age                   float64
SibSp                   int64
Parch                   int64
Ticket         string[python]
Fare                  float64
Cabin          string[python]
Embarked       string[python]
dtype: object

# Verify categorical values

In [62]:
# Verify categorical values
print("Sex:", cleaned_df["Sex"].unique())
print("Embarked:", cleaned_df["Embarked"].unique())

# Verify numerical ranges
print("\nAge range:", cleaned_df["Age"].min(), "to", cleaned_df["Age"].max())
print("Fare range:", cleaned_df["Fare"].min(), "to", cleaned_df["Fare"].max())

# Verify passenger IDs
print("\nPassenger ID data type:", cleaned_df["PassengerId"].dtype)

Sex: <StringArray>
['Male', 'Female']
Length: 2, dtype: string
Embarked: <StringArray>
['Q', 'S', 'C']
Length: 3, dtype: string

Age range: 0.17 to 76.0
Fare range: 0.0 to 512.3292

Passenger ID data type: string

In [63]:
# Save the cleaned dataset as a new CSV file
output_file = "tested_cleaned.csv"

cleaned_df.to_csv(
    output_file,
    index=False
)

print("Cleaned dataset saved successfully!")
print("File name:", output_file)

Cleaned dataset saved successfully!
File name: tested_cleaned.csv

# Read the saved cleaned file again

In [64]:
# Read the saved cleaned file again
final_df = pd.read_csv("tested_cleaned.csv")

# Verify exported file
print("Shape:", final_df.shape)
print("Missing values:", final_df.isnull().sum().sum())
print("Duplicate rows:", final_df.duplicated().sum())

# Display first 5 records
final_df.head()

Shape: (418, 12)
Missing values: 0
Duplicate rows: 0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",Male,34.5,0,0,330911,7.8292,Unknown,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",Female,47.0,1,0,363272,7.0000,Unknown,S
2,894,0,2,"Myles, Mr. Thomas Francis",Male,62.0,0,0,240276,9.6875,Unknown,Q
3,895,0,3,"Wirz, Mr. Albert",Male,27.0,0,0,315154,8.6625,Unknown,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",Female,22.0,1,1,3101298,12.2875,Unknown,S

# 🏁 Conclusion

This project successfully demonstrates a complete **data cleaning and preprocessing workflow using Python, Pandas, NumPy, and Jupyter Notebook**. The raw dataset was systematically examined to identify missing values, duplicate records, inconsistent formatting, incorrect data types, invalid values, and potential outliers.

Missing values were handled using appropriate techniques such as **median imputation and categorical replacement**, while duplicate records were checked and removed where necessary. Text and categorical values were standardised to maintain consistency, and data types were corrected according to the meaning of each variable. Potential numerical outliers were identified using the **IQR method** and carefully reviewed rather than being automatically removed.

A **before-vs-after data quality comparison** confirmed the improvements achieved during preprocessing. The final dataset contains **no missing values or duplicate rows**, has consistent formatting and appropriate data types, and preserves valid observations.

Overall, the project transformed the raw dataset into a **clean, consistent, validated, and analysis-ready dataset**, providing a reliable foundation for further **Exploratory Data Analysis (EDA), data visualisation, statistical analysis, and machine-learning applications**.